from __future__ import annotations

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, TextAreaField, FileField
from wtforms.validators import DataRequired, Email, Length, Optional


class RegisterForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email(), Length(max=255)])
    password = PasswordField("Password", validators=[DataRequired(), Length(min=8, max=128)])


class LoginForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])


class DIDCreateForm(FlaskForm):
    company = StringField("Company", validators=[DataRequired(), Length(max=255)])
    website = StringField("Website", validators=[Optional(), Length(max=2048)])
    twitter = StringField("Twitter", validators=[Optional(), Length(max=1024)])
    discord = StringField("Discord", validators=[Optional(), Length(max=1024)])
    # Optional additional company details
    legal_name = StringField("Legal Name", validators=[Optional(), Length(max=255)])
    industry = StringField("Industry", validators=[Optional(), Length(max=255)])
    country = StringField("Country/Region", validators=[Optional(), Length(max=255)])
    registration_number = StringField("Registration Number", validators=[Optional(), Length(max=255)])
    contact_email = StringField("Contact Email", validators=[Optional(), Email(), Length(max=255)])
    contact_url = StringField("Contact URL", validators=[Optional(), Length(max=2048)])
    description = TextAreaField("Description", validators=[Optional(), Length(max=2000)])
    # Company-level DID only; no policy/asset/RWA here
    # Key is generated by the platform and offered as a one-time download


class ApproveForm(FlaskForm):
    notes = TextAreaField("Notes", validators=[Optional(), Length(max=2000)])


class ForgotPasswordForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])


class ResetPasswordForm(FlaskForm):
    token = StringField("Token", validators=[DataRequired()])
    new_password = PasswordField("New Password", validators=[DataRequired(), Length(min=8, max=128)])


class UploadDocForm(FlaskForm):
    file = FileField("Document")


class CreateCredentialForm(FlaskForm):
    label = StringField("Label", validators=[DataRequired(), Length(max=255)])
    # Require Policy ID for strong scoping of the credential
    policy_id = StringField("Policy ID", validators=[DataRequired(), Length(min=20, max=128)])
    asset_name = StringField("Asset Name", validators=[Optional(), Length(max=255)])
    rwa_asset_type = StringField("RWA Asset Type", validators=[Optional(), Length(max=255)])
    rwa_jurisdiction = StringField("RWA Jurisdiction", validators=[Optional(), Length(max=255)])
    rwa_registration = StringField("RWA Registration", validators=[Optional(), Length(max=255)])
    # Either upload key file or paste passphrase
    key_file = FileField("Key file (preferred)")
    key_passphrase = PasswordField("Passphrase", validators=[Optional(), Length(min=8, max=128)])
